version: '3.7'

services:
  server:
    build: "./"
    image: "${IMAGE_NAME}:${IMAGE_VERSION}"
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "100m"
    env_file:
     - .env
    ports:
      - "2021:3000"
    restart: on-failure
    environment:
      TZ: "Asia/Jakarta"
      APP_PORT: 3000 
      #base_url perlu untuk mengetahui di host dev/staging/production
      APP_BASE_URL: "http://localhost:2021"

      #database config
      DB_HOST: "localhost"
      DB_PORT: "3306"
      DB_USER: "root"
      DB_PASS: ""
      DATABASE: "ecom_portal"

      #redis config
      REDIS_HOST: "1asagna.fira.id"
      REDIS_PORT: 6379
      REDIS_PASS: ""
    
